### ISSUE TITLE
Generate correct URIs

### ISSUE THREAD

**Issue by dachafra** [oeg-upm/Morph-KGC#1]
Encode the URIs for subject and templates correctly (e.g., example.org/NEW YORK --> example.org/NEW%20YORK)

Have a parameter in the config like:

```
uri.encode=(" "->"%20"),,(","->""),,("á"->"a"),,("é"->"e"),,("í"->"i"),,("ó"->"o"),,("ú"->"u"),,("ü"->"u"),,("ñ"->"n"),,("\u00B4"->"%C2%B4")
```
Morph-RDB has it.

**Comment by ArenasGuerreroJulian** [comment]
quote() generates URIs correctly and its overhead is very little. I close the issue.

**Comment by ArenasGuerreroJulian** [comment]
quote() generates URIs correctly and its overhead is very little. I close the issue.
