### ISSUE TITLE
BUG: Small error in example mapping for GTFS

### ISSUE THREAD

**Issue by magbak** [oeg-upm/morph-kgc#139]
Query 1 in the GTFS benchmark has zero results under the example mapping in this repo. 
This is query 1: 
```
SELECT * WHERE {
	?shape a gtfs:Shape .
	?shape gtfs:shapePoint ?shapePoint .
	?shapePoint geo:lat ?shape_pt_lat .
	?shapePoint geo:long ?shape_pt_lon .
	?shapePoint gtfs:pointSequence ?shape_pt_sequence .
}
```

It is due to this problem around line 783 in https://github.com/oeg-upm/morph-kgc/blob/main/examples/csv/mapping.csv.ttl

:om_074 a rr:ObjectMap;
    rr:template "http://transport.linkeddata.es/madrid/metro/shape_point/{shape_id}-{shape_pt_sequence}";
    rr:termType rr:Literal.

But the term type should be an IRI:

:om_074 a rr:ObjectMap;
    rr:template "http://transport.linkeddata.es/madrid/metro/shape_point/{shape_id}-{shape_pt_sequence}";
    rr:termType rr:IRI.

**Comment by arenas-guerrero-julian** [comment]
Hi @magbak ,

Thanks for reporting this. I fixed it, hope it works now.
