### ISSUE TITLE
DOC: Include examples of other DBs

### ISSUE THREAD

**Issue by paoespinozarias** [oeg-upm/morph-kgc#54]
####  Where in the Documentation?
[https://github.com/oeg-upm/morph-kgc/tree/main/examples](https://github.com/oeg-upm/morph-kgc/tree/main/examples)

####  Suggested Fix for Documentation
It would be helpful to have more examples of how to set up connection to other databases. For example, I'm working with Microsoft SQL and the connection would be something like this `db_url=mssql+pymssql://user:password@server.net/db_name`

**Comment by ArenasGuerreroJulian** [comment]
Hi @paoespinozarias ,

Thanks for the feedback, some more information is available [here](https://github.com/oeg-upm/Morph-KGC/wiki/Relational-Databases), but  I agree more clear examples are needed (without redirecting to SQLAlchemy docs). I will work on this has soon as possible :)

Julián

**Comment by ocorcho** [comment]
Hi @paoespinozarias 

Feel free to add those ones with a pull request if you wish. We will review them and add them if relevant.

**Comment by ArenasGuerreroJulian** [comment]
Hi @paoespinozarias ,

There is a new documentation available. I have added some examples on these. Please, if you think that the documentation can still be improved do not hesitate to reopen the issue or create a new one.

Julián
