### ISSUE TITLE
BUG: Named Graph can't be created

### ISSUE THREAD

**Issue by cutterkom** [oeg-upm/morph-kgc#56]
####  What Happens?
Creating a named graph using YARRRML does not work (https://rml.io/yarrrml/tutorial/getting-started/#how-to-add-triples-to-a-graph).

The error `Found an invalid graph termtype. Found values ['http://www.w3.org/ns/r2rml#Literal']. Graph maps must be http://www.w3.org/ns/r2rml#IRI.` appears when using `morph-kgc` (within `kglab`)

#### To Reproduce
[test.csv](https://github.com/oeg-upm/morph-kgc/files/8253585/test.csv)

I am building a YARRRML rules file called rules.yml:
```YAML
prefixes:
  ex: http://example.com/
  schema: https://schema.org/

mappings:
  TestMapping:
    sources: 
      - [test.csv~csv]
    graph: ex:named_graph # this is the lines that breaks the workflow
    s: ex:$(id)
    po:
      - [schema:name, $(name)]
      - [schema:type, $(type)]
```

I convert this to a `rml` using the `yarrrml-parser` (`yarrrml-parser -i rules.yml -o mapping.rml.ttl `). This results in this mapping.rml file

```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#>.
@prefix fno: <https://w3id.org/function/ontology#>.
@prefix d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>.
@prefix void: <http://rdfs.org/ns/void#>.
@prefix dc: <http://purl.org/dc/terms/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix : <http://mapping.example.com/>.
@prefix ex: <http://example.com/>.
@prefix schema: <https://schema.org/>.

:rules_000 a void:Dataset;
    void:exampleResource :map_TestMapping_000.
:map_TestMapping_000 rml:logicalSource :source_000.
:source_000 a rml:LogicalSource;
    rml:source "test.csv";
    rml:referenceFormulation ql:CSV.
:map_TestMapping_000 a rr:TriplesMap;
    rdfs:label "TestMapping".
:s_000 a rr:SubjectMap.
:map_TestMapping_000 rr:subjectMap :s_000.
:s_000 rr:template "http://example.com/{id}";
    rr:graphMap :gm_000.
:gm_000 a rr:GraphMap;
    rr:constant "http://example.com/named_graph".
:pom_000 a rr:PredicateObjectMap.
:map_TestMapping_000 rr:predicateObjectMap :pom_000.
:pm_000 a rr:PredicateMap.
:pom_000 rr:predicateMap :pm_000.
:pm_000 rr:constant schema:name.
:pom_000 rr:objectMap :om_000.
:om_000 a rr:ObjectMap;
    rml:reference "name";
    rr:termType rr:Literal.
:pom_001 a rr:PredicateObjectMap.
:map_TestMapping_000 rr:predicateObjectMap :pom_001.
:pm_001 a rr:PredicateMap.
:pom_001 rr:predicateMap :pm_001.
:pm_001 rr:constant schema:type.
:pom_001 rr:objectMap :om_001.
:om_001 a rr:ObjectMap;
    rml:reference "type";
    rr:termType rr:Literal.
```

I use this small script to create the RDF triples:

```python
import kglab

namespaces = {
    "ex":  "http://example.com/",
    "schema": "https://schema.org/"
    }
kg = kglab.KnowledgeGraph(
    name = "A KG example",
    namespaces = namespaces,
    )
kg.materialize('config.ini')
kg.save_rdf("rdf-triples.ttl")
```

The `config` file contains:

```
[CONFIGURATION]
logging_level=DEBUG

[DataSource1]
mappings=mapping.rml.ttl
```

#### Environment (please complete the following information):
 - OS: MacOS 12.2.1 
 - Python version: 3.9.10
 - Morph-KGC version: 1.6.0 (kglab 0.4.4)

**Comment by ArenasGuerreroJulian** [comment]
Hi @cutterkom ,

Thanks for the very well detailed issue. I will take a look as posible to it.

Julián

**Comment by ArenasGuerreroJulian** [comment]
Hi @cutterkom ,

I have taken a look at this issue. It is not a problem of Morph-KGC but of the RML mapping. The line:

```
rr:constant "http://example.com/named_graph".
```

is not correct, it should be

```
rr:constant <http://example.com/named_graph>.
```

To ensure that an IRI is genarated. I have tried it and works with no error. As specified by the [R2RML specification](https://www.w3.org/TR/r2rml/):

_Constant-valued term maps are not considered as having a term type, and specifying rr:termType on these term maps has no effect. The type of the generated RDF term is determined directly by the value of rr:constant: If it is an IRI, then an IRI will be generated; if it is a literal, a literal will be generated._

I do not know if the yarrrml itself is missing something or if the yarrrml-parser has some bug, maybe @DylanVanAssche , @bjdmeest or @pheyvaer can help with this question.

Julián

**Comment by cutterkom** [comment]
Ok, thanks for looking into it!

**Comment by pheyvaer** [comment]
At first sight it does seem like a bug in the YARRRML-Parser. Could you create an issue in [the repo](https://github.com/rmlio/yarrrml-parser) for that? Thanks!

**Comment by dachafra** [comment]
@pheyvaer does it make sense to just transfer this one?

**Comment by pheyvaer** [comment]
I don't know if that is even possible if there are not in the same organization.

**Comment by ArenasGuerreroJulian** [comment]
I have created an [issue](https://github.com/RMLio/yarrrml-parser/issues/154) in the yarrrml-parser repo.

Thanks all! :)
