### ISSUE TITLE
QST: The csv-example appears to have "bad" data that breaks RDFLIB triples parsing.

### ISSUE THREAD

**Issue by nraphael** [oeg-upm/morph-kgc#60]
The ntriples.py parser from rdflib fails at the first data point in AGENCY.csv. I believe one must either change the mapping spec, provide for specifying a base uri to morph_kgc or simply tweak the data. But this must have all worked at some point.

Specifically, this triple doesn't parse (and it it not the only such case):
<http://transport.linkeddata.es/madrid/agency/00000000000000000001> <http://vocab.gtfs.org/terms#fareUrl> <00000000000000000001> .

because the object is a relative IRI and ntriples.py checks for an absolute IRI:

  File "[]/PycharmProjects/morph-kgc/venv/lib/python3.8/site-packages/rdflib/plugins/parsers/ntriples.py", line 251, in uriref
    uri = self.eat(r_uriref).group(1)
  File "[]//PycharmProjects/morph-kgc/venv/lib/python3.8/site-packages/rdflib/plugins/parsers/ntriples.py", line 226, in eat
    raise ParseError("Failed to eat %s at %s" % (pattern.pattern, self.line))
rdflib.exceptions.ParserError: Failed to eat <([^:]+:[^\s"<>]*)> at <00000000000000000001>.

I am running:
+ morph_kgc git commit1ddf2ef6d12aa47f5e956756c8ea1a8cb7c18761
+ rdflib 6.1.1+
+ python 3.8.

Thank you, by the way, for your work.

**Comment by dachafra** [comment]
@nraphael I assume you are using the GTFS-Madrid-Bench right? Can you point us to which mapping are you using and which datasets or how you generate them?  

I think this is an old problem in the generation of the data in the benchmark, which is already resolved.

**Comment by nraphael** [comment]
Thank you @dachafra. In answer to the email question I got a moment ago (though you may have already answered it yourself), I was using the data from the csv-examples folder of the repository package itself -- with file paths suitably modified.

**Comment by dachafra** [comment]
made a PR solving the problem. let's wait for @ArenasGuerreroJulian to approval it

**Comment by dachafra** [comment]
solved!

**Comment by ArenasGuerreroJulian** [comment]
Thanks for spotting this @nraphael!
