### ISSUE TITLE
BUG: Double Join condition throws error

### ISSUE THREAD

**Issue by ramcaat** [oeg-upm/morph-kgc#62]
####  What Happens?
I installed morph-kgc 2.0.1 and it changed the way the double join condition worked. The same RML works in 1.6.0.  If I have two join condition in RML it throws an error

Example of double join : https://github.com/semantifyit/RocketRML/blob/ca8c3724dac16764a8d8d03722e732eba46a471b/tests/doubleJoinCondition/mapping.ttl

Error

aise ValueError("cannot join with no overlapping index names")
ValueError: cannot join with no overlapping index names

Code snippet

rr:predicateObjectMap [
        rr:predicate example:xyz;
        rr:objectMap [
    rr:parentTriplesMap <#xyz>;
       
            rr:joinCondition [
            rr:child "column1";
            rr:parent "column1";
            ];
        rr:joinCondition [
            rr:child "column2";
            rr:parent "column2";
            ];
        ];
    ];

#### Environment (please complete the following information):
 - OS: Wiindows
 - Python version: 3.9
 - Morph-KGC version: 2.0.1

**Comment by ArenasGuerreroJulian** [comment]
Hi @ramcaat ,

Thanks for spotting the error. Indeed, I reimplemented joins in v2.0.0. I will try to solve it and also add the test case you point to to the continuous integration pipeline.

Julián

**Comment by ArenasGuerreroJulian** [comment]
Hi @ramcaat ,

I have solved this in v2.1.1.

**Comment by ramcaat** [comment]
Thanks @ArenasGuerreroJulian. Will test it

**Comment by ramcaat** [comment]
Thanks we tested and it works
