### ISSUE TITLE
QST:  Errors in the RDF file generating on Windows

### ISSUE THREAD

**Issue by TereLaguinge** [oeg-upm/morph-kgc#65]
Hi! 
Hope you're well! I'm running morph-kgc on a json file (of Associations of Open Target). I ran it on the same json file (in command line):
![image](https://user-images.githubusercontent.com/69465938/167726416-c114be55-cdf8-4e21-bc00-40f16872f30d.png)

The first time I got errors on the output:
![image](https://user-images.githubusercontent.com/69465938/167727274-1781980f-8ef2-4f86-8956-cac6708fd7a0.png)

I got this random lines that are wrong so when I tried to upload that ouput file with errors to graphDB, I can't. I got this malformed output files with multiple jsons. Sometimes if I ran morph-kgc once more it corrects and I get a correct output file which I can upload to GraphDB. However, sometimes I get it wrong with that weird lines and can't form it correctly.
I attach the mapping file, the json files I'm trying to convert and the outputs I obtained. 

Do you know how can I do to fix it? 

Thanks in advance for your help!

Best, 
Tere Laguinge
[github.zip](https://github.com/oeg-upm/morph-kgc/files/8665237/github.zip)

**Comment by ArenasGuerreroJulian** [comment]
Hi @TereLaguinge ,

Could you please try if the problem persists with the following configuration?

```
[CONFIGURATION]
number_of_processes=1

[DataSourceJSON]
mappings=OAtrial.json.ttl
file_path=data_100_5.json
```

Thanks,
Julián

**Comment by ArenasGuerreroJulian** [comment]
Hi again @TereLaguinge ,

I think that this might be related to [file buffers](https://stackoverflow.com/questions/7127075/what-exactly-is-file-flush-doing#answer-7127162). I am flushing now everything to disk on file close. I have tested it and it is generating the correct triples for me with your original `config.ini` (i.e. without `number_of_processes=1`). You can test it [installing from source](number_of_processes=1), and if it works I can create a release.

Julián

**Comment by TereLaguinge** [comment]
Hi Julian! 

First, I uninstall morph-kgc by running: pip uninstall morph-kgc

Then, I reinstall it doing this:
1. cloning the repository
2. going to the folder morph-kgc
3. running : python setup.py install:
![image](https://user-images.githubusercontent.com/69465938/167886979-c7209a62-c452-4641-a8fe-39cae0d5ea49.png)
![image](https://user-images.githubusercontent.com/69465938/167887001-fe534082-0a3b-4968-87b9-0a4f1fd8f33f.png)

Then I ran morph-kgc for the data.json and still get errors in the output:
![image](https://user-images.githubusercontent.com/69465938/167887214-2b3cd0e4-64e3-4ded-b301-291d5ca3c4fc.png)


I'm runnning it with this config file:
![image](https://user-images.githubusercontent.com/69465938/167887282-1c879a6a-fed0-4939-a004-f3692fd483c7.png)

However, when I include this to the configuration file:

`[CONFIGURATION]
number_of_processes=1

[DataSourceJSON]
mappings=OAtrial.json.ttl
file_path=data.json`

It ran ok and it created a correct rdf output file.

Thanks a lot for your help!
Best, 
Tere Laguinge

**Comment by ArenasGuerreroJulian** [comment]
Hi @TereLaguinge ,

Thank for testing and the very detailed answer :)

As I see from the screenshot of notepad you are running on windows. Could you confirm? I think the issue is related to how file operations are handled by windows (e.g. not allowing two processes to open the same file at once).

Thanks,
Julián

**Comment by Ardark27** [comment]
It works for me:
- mapping: https://github.com/osoc-es/c2t/blob/main/mappings/mappingSyft.yarrrml
- config:  https://github.com/osoc-es/c2t/blob/main/config.ini

**Comment by ArenasGuerreroJulian** [comment]
This is related to non-atomic write operation in Windows. It is now solved with a mutex.
