### ISSUE TITLE
QST: contain or like operator in jsonpath

### ISSUE THREAD

**Issue by layman71** [oeg-upm/morph-kgc#66]
Hi, I am new to this tech and I have a question. Can I use operators like contains ,=~ in rml:iterator for jsonpath to filter data. If yes, please direct me to an example. Thanks in advance.

Ex - rml:iterator "$[?(@.column **contains** \"cat\" )]";

**Comment by ArenasGuerreroJulian** [comment]
Hi @layman71 ,

You can take a look to the filter operators supported with examples **[here](https://github.com/zhangxianbing/jsonpath-python#filter-expression)**.

Julián

**Comment by ArenasGuerreroJulian** [comment]
Hi @layman71 ,

Unfortunately, the support of JSONpath in morph-kgc is limited mainly due to the lack of libraries in python. We will keep an eye on updates to JSONpath libraries (or new libraries) so that they can be integrated in morph-kgc.

For the moment I close this issue.
