### ISSUE TITLE
QST: How is RDF-Star support accomplished?

### ISSUE THREAD

**Issue by lambdakris** [oeg-upm/morph-kgc#70]
Hi, just a simple question. I was just curious how the support for RDF-Star is accomplished since to the best of my knowledge, neither rdflib nor pyoxigraph have support for RDF-Star.

**Comment by ArenasGuerreroJulian** [comment]
Hi @lambdakris ,

Indeed, RDFlib does not support RDF-star, but pyoxigraph does (since version  [0.3.0](https://github.com/oxigraph/oxigraph/releases/tag/v0.3.0)).

Also when executing Morph-KGC via command line, RDF-star is also supported since RDFlib and Oxigraph are not needed.

Julián

**Comment by lambdakris** [comment]
Ah excellent! Thank you for the answer @ArenasGuerreroJulian. Much appreciated.
