### ISSUE TITLE
QST: Possible to suppress automatic creation of namespaces?

### ISSUE THREAD

**Issue by gaspanico** [oeg-upm/morph-kgc#71]
I'm generating some Turtle files, and due to the nature of my mapping, with a large number of unique URIs, morph-kgc ends up creating thousands of namespaces {ns1, ns2, ns3, ..., nsN}. This unfortunately becomes a problem when I later try to import the files into my graph database, since GraphDB automatically adds the namespaces to the repository.

Is there any way of suppressing this automatic creation of namespaces?

Excerpt of output below:

```
@prefix ns1: <http://semanticscience.org/resource/> .
@prefix ns2: <http://rdf.OpenTargets.org/tda-85258977fb3e9d0a49f584ebea0e1170/> .
@prefix ns3: <http://rdf.OpenTargets.org/> .
@prefix ns4: <http://rdf.OpenTargets.org/tda-4270e7cd9384040dd557676c5aa2fbaf/> .
@prefix ns5: <http://rdf.OpenTargets.org/tda-1ee263036cf3f0dd8af7ab22699a1015/> .
@prefix ns6: <http://rdf.OpenTargets.org/tda-bff7ca55af7bfe8025f47ba0f25ea95c/> .
@prefix ns7: <http://rdf.OpenTargets.org/tda-b9404ae8f20199b405fd5d40a5a12f60/> .

ns3:tda-1ee263036cf3f0dd8af7ab22699a1015 a ns3:TargetDiseaseAssociation ;
    ns5:gene2phenotype ns3:gene2phenotype ;
    ns5:genetic_association ns3:genetic_association .

ns5:gene2phenotype ns1:SIO_001277 <http://rdf.OpenTargets.org/tda-1ee263036cf3f0dd8af7ab22699a1015/gene2phenotype/indirectData> .

ns3:tda-4270e7cd9384040dd557676c5aa2fbaf a ns3:TargetDiseaseAssociation ;
    ns4:gene_burden ns3:gene_burden ;
    ns4:genetic_association ns3:genetic_association .

ns4:gene_burden ns1:SIO_001277 <http://rdf.OpenTargets.org/tda-4270e7cd9384040dd557676c5aa2fbaf/gene_burden/indirectData> .
```

**Comment by ArenasGuerreroJulian** [comment]
HI @gaspanico ,

Morph-KGC output format is N-TRIPLES and N-QUADS, is this snippet the output generated by Morph-KGC?

**Comment by gaspanico** [comment]
Hi @ArenasGuerreroJulian 

Sorry, it hadn't occurred to me that the guilty one here would be rdflib.serialize, not morph_kgc. I use the below snippet for generating my files:

```
config = f'[CONFIGURATION]\nnumber_of_processes=1\noutput_file={output_file}\n[DataSourceJSON]\nmappings={mapping_file}\nfile_path={input_file}'

rdf = morph_kgc.materialize(config)
rdf.serialize(destination=output_file, format="ttl")
```

**Comment by dachafra** [comment]
Exactly @gaspanico, it is from RDFlib, nothing related to our tool ;-) You should be able to add your own namespaces over the generated graph: https://rdflib.readthedocs.io/en/stable/namespaces_and_bindings.html

I think we can close this issue @ArenasGuerreroJulian

**Comment by ArenasGuerreroJulian** [comment]
@gaspanico In the case you are executing as a library you can also use pyoxigraph instead of RDFlib with `materialize_oxigraph`

Julián
