### ISSUE TITLE
ENH: If someone tries to use morph with a .rml file, assume it's a turtle file

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/morph-kgc#80]
#### Is your Feature Request Related to a Problem?
Many students get confused with `.rml` and `.ttl`. `.rml` may not be a valid extension, but many potential users use `.rml` as their mapping file. And right now morph fails if that's the case.

#### Describe the Solution you'd Like
If someone provides a `.rml` file, or `.txt` file as mappings, try to run morph-kgc assuming it's a turtle file.
Ideally, try to parse the mapping file in different serializations if the extension is not clear.

**Comment by ArenasGuerreroJulian** [comment]
This is now fixed and a test case, which is passing, has been added. It will be available in the next release.

**Comment by dgarijo** [comment]
Awesome, thanks!
