### ISSUE TITLE
ENH: Allow CSVs with ";" as separator

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/morph-kgc#81]
#### Is your Feature Request Related to a Problem?
CSVs with ";" produce an error when using morph-kgc. 

#### Describe the Solution you'd Like
I would like to support ";" as a separator in CSV files. Some students where having problems figuring this out

**Comment by ArenasGuerreroJulian** [comment]
Hi, currently morph-kgc only supports CSV and TSV, we will see how to add an option for any separator

**Comment by dgarijo** [comment]
Thanks

**Comment by ArenasGuerreroJulian** [comment]
This has been solved and will be available in the next release. If you need the functionality right away, please [install from source](https://morph-kgc.readthedocs.io/en/latest/documentation/#from-source).

**Comment by dgarijo** [comment]
awesome thanks
