### ISSUE TITLE
BUG: Blank node subject map without rr:template causes exception

### ISSUE THREAD

**Issue by lucascool12** [oeg-upm/morph-kgc#82]
####  What Happens?
A triples map that has a subject map with a blanknode as term type causes an exception if there is no rr:template in the subject map.

#### To Reproduce
Steps to reproduce the behavior. If possible include sample data, mappings and configuration used.
A triples map with a subject map as blanknode without rr:template in subject map.
[blankNodeExample.csv](https://github.com/oeg-upm/morph-kgc/files/9862608/blankNodeExample.csv)
Mapping:
```
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

_:b a rr:TriplesMap;
    rml:logicalSource[
        rml:referenceFormulation <http://semweb.mmlab.be/ns/ql#CSV>;
        rml:source "test.csv"
    ];
    rr:subjectMap [
        # rr:template "{id}";
        rr:termType rr:BlankNode
    ];
    rr:predicateObjectMap [
        rr:predicate foaf:firstName;
        rr:objectMap [
            rml:reference "given_name"
        ]
    ].
```
Config:
[DataSourceCSV]
mappings=blankNodeExample.ttl

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04.5 LTS on Windows 10 x86_64
 - Python version: 3.10.8
 - Morph-KGC version: 2.2.0

**Comment by ArenasGuerreroJulian** [comment]
Hi @lucascool12 

As far as I know, the behaviour of morph-kgc is the standard of the [R2RML Recommendation](https://www.w3.org/TR/r2rml/). A term map must be provided a constant, column/reference or a template.

However, I think the [rmlmapper](https://github.com/RMLio/rmlmapper-java) does support this mapping syntax as an extended functionality. Maybe @DylanVanAssche can confirm this?

Why do you need this functionality? What is the limitation of standard [R2]RML for your use case?

Julián

**Comment by dachafra** [comment]
In any case, it's good to mention that the W3C community group on KGC agreed that in the next version of RML this feature will be allowed ([see here](https://github.com/kg-construct/collection-containers-spec/issues/24)), but this will require extra effort to implement it as references would be maintained in memory if there is any join.
