### ISSUE TITLE
BUG: JSON with empty arrays does not create all triples 

### ISSUE THREAD

**Issue by ramcaat** [oeg-upm/morph-kgc#86]
For some reason configuration.instanceType does not generate a triple.. I tried JSONpath and it works there.. Not sure what issue is here. Thanks for helping

Mapping ==>

<#MAIN>
rml:iterator "$"
rml:referenceFormulation ql:JSONPath.

<#Mapping>
rml:logicalSource <#MAIN>
 a rr:TripleMap;

 rr:SubjectMap [
     rr:template "http:/example.com/{resourceId}"
     rr:class ex:Ec2Instance
 ];

 rr:predicateObjectMap[
     rr:predicate ex:InstanceType
     rr:objectMap [
         rr:reference "configuration.instanceType" **# DOES NOT GENERATE TRIPLE**
     ]
 ]

Input.json
========

{
    "name": "AWS",
    "type": "EC2",
    "resourceId":"I-ajhhjvnbjkh",
    "Configuration":{
       "productCodes" :[]
        "instanceType" : "4xLarge",
        "virualization": "evm"
    }
}

**Comment by ramcaat** [comment]
This issue occurs if there is a empty json element in the nested json.

**Comment by ArenasGuerreroJulian** [comment]
Hi @ramcaat ,

Mind the mapping syntax, e.g. it is not `rr:reference` but `rml:reference`. Correct version of the mapping:

```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix ex: <http://example.es/>.

<#Mapping>
  rml:logicalSource [
    rml:source "data.json" ;
    rml:iterator "$";
  ];
  rr:subjectMap [
    rr:template "http:/example.com/{resourceId}";
    rr:class ex:Ec2Instance
  ];
  rr:predicateObjectMap [
    rr:predicate ex:InstanceType;
    rr:objectMap [
      rml:reference "configuration.instanceType"
    ]
  ].
 ```

I will look into this error as soon as I can.

Julián

**Comment by ramcaat** [comment]
Ya that is my bad but the triples are not generated for the elements  after an empty array

**Comment by dachafra** [comment]
@ramcaat you are missing a comma in your JSON
```
{
"name": "AWS",
"type": "EC2",
"resourceId":"I-ajhhjvnbjkh",
"Configuration":{
"productCodes" :[] , <-- here
"instanceType" : "4xLarge",
"virualization": "evm"
}
}
```

**Comment by ramcaat** [comment]
What I am working with in system is a good json but I can't share but the statement is correct

**Comment by jatoledo** [comment]
Hi @ramcaat , Thank you for using morph-kgc.

I have tested this mapping and it works.

```bash
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix ex: <http://example.es/>.

<#Mapping>
  rml:logicalSource [
    rml:source "data.json" ;
    rml:iterator "$";
  ];
  rr:subjectMap [
    rr:template "http:/example.com/{resourceId}";
    rr:class ex:Ec2Instance
  ];
  rr:predicateObjectMap [
    rr:predicate ex:InstanceType;
    rr:objectMap [
      rml:reference "configuration.instanceType"
    ]
  ].
```

Result:

```bash
<http:/example.com/I-ajhhjvnbjkh> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.es/Ec2Instance>.
```

Can you test with this mapping?  I recommend you  the examples that are in this link https://rml.io/specs/rml/#example-JSON

And another not minor point. [R2RML ](https://www.w3.org/TR/r2rml/)is RDB to RDF Mapping Language and you are using JSON(RML extends R2RML).

**Comment by ArenasGuerreroJulian** [comment]
Thanks @dachafra @jatoledo for trying. I will have a look to this as soon as I can.

**Comment by ArenasGuerreroJulian** [comment]
Please @ramcaat, can you try using `rml:iterator "$.*"`?

**Comment by dachafra** [comment]
@ArenasGuerreroJulian I've already done it for my tests. Here are the mapping and data
[data-mapping.zip](https://github.com/oeg-upm/morph-kgc/files/10020997/data-mapping.zip)

**Comment by ArenasGuerreroJulian** [comment]
This is working for me returning 1 triple

**Comment by dachafra** [comment]
It has to return two. One for the class, another for the POM, it only returns the class one

**Comment by ArenasGuerreroJulian** [comment]
This is now solved,

@ramcaat you can install via 

`pip install git+https://github.com/oeg-upm/morph-kgc.git`

until next release

**Comment by ramcaat** [comment]
I am sorry. Confused. How is this fixed? What is the fix ?

**Comment by dachafra** [comment]
@ramcaat JSONs with empty arrays now generate all the RDF triples, which is the issue you had. This is fixed because @ArenasGuerreroJulian has modified the code of the engine and pushed the changes to the main repo. There is still no new release so if you want to use it you have to install it from the source code (not PyPi) as it's indicated in the previous comment

**Comment by ramcaat** [comment]
Thanks @dachafra

**Comment by ramcaat** [comment]
@ArenasGuerreroJulian i can't use the new code unless there is a release. Thanks for your great work. Looking forward for release soon
