### ISSUE TITLE
ENH: Remove object/subject_quoted and use object/subject_map_value and object/subject_map_type instead

### ISSUE THREAD

**Issue by ahmad88me** [oeg-upm/morph-kgc#87]
#### Describe the Solution you'd Like
Remove object/subject_quoted and use object/subject_map_value and object/subject_map_type instead

#### Additional Context
To simplify the parsing of the mappings.

**Comment by ahmad88me** [comment]
Sounds good

**Comment by ArenasGuerreroJulian** [comment]
The parsing of logical sources has been compacted:
- `logical_source_type` can be `rr:tableName`, `rml:query` or `rml:source`
- `logical_source_value`

This also simplifies a bit the materializer
